"""added images in user table

Revision ID: 35696cf299a2
Revises: cae261db5e0a
Create Date: 2021-06-24 18:43:04.359202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35696cf299a2'
down_revision = 'cae261db5e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image')
    # ### end Alembic commands ###
