"""added table

Revision ID: ca3bccfa6133
Revises: e8f1d0543f5a
Create Date: 2021-06-24 15:11:47.388893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca3bccfa6133'
down_revision = 'e8f1d0543f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'name')
    # ### end Alembic commands ###
