"""insertion of image table

Revision ID: cae261db5e0a
Revises: ca3bccfa6133
Create Date: 2021-06-24 17:43:27.863721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae261db5e0a'
down_revision = 'ca3bccfa6133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myblogs', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myblogs', 'image')
    # ### end Alembic commands ###
