"""create realtionships on tables

Revision ID: ee8617bba9c8
Revises: 6221039e453b
Create Date: 2021-06-22 16:58:02.447933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee8617bba9c8'
down_revision = '6221039e453b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('myblogs_user_id_fkey', 'myblogs', type_='foreignkey')
    op.drop_column('myblogs', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('myblogs', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('myblogs_user_id_fkey', 'myblogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
